;;; helsing-theme.el --- Helsing for Doom Emacs -*- lexical-binding: t; no-byte-compile: t; -*-
;;
;; Generated from docs/helsing-palette.yml via generator/generate.py.
;; Do not edit this file by hand.

(require 'doom-themes)

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-directory load-file-name)))

(defgroup helsing-theme nil
  "Options for the Helsing Doom Emacs theme."
  :group 'doom-themes)

(def-doom-theme helsing
  "A disciplined daylight theme with paper warmth and semantic restraint."
  :family 'helsing
  :background-mode 'light

  ((bg         '("#F4F1EA" "white" "white"))
   (fg         '("#2A2A2A" "black" "black"))
   (bg-alt     '("#EAE5DC" "white" "white"))
   (fg-alt     '("#6B6B6B" "black" "brightblack"))

   (base0      '("#FBF9F4" "white" "white"))
   (base1      '("#F4F1EA" "white" "white"))
   (base2      '("#EAE5DC" "white" "white"))
   (base3      '("#D6D0C4" "brightblack" "brightblack"))
   (base4      '("#B8B1A7" "brightblack" "brightblack"))
   (base5      '("#A8A29E" "brightblack" "brightblack"))
   (base6      '("#6B6B6B" "brightblack" "brightblack"))
   (base7      '("#4A4742" "black" "black"))
   (base8      '("#2A2A2A" "black" "black"))

   (grey       base4)
   (muted      '("#6B6B6B" "black" "brightblack"))
   (subtle     '("#A8A29E" "brightblack" "brightblack"))
   (border     '("#D6D0C4" "brightblack" "brightblack"))
   (info       '("#4A90E2" "brightblue" "brightblue"))
   (red        '("#C23B3B" "red" "red"))
   (orange     '("#C47A2C" "brightred" "brightred"))
   (green      '("#4C9A5F" "green" "green"))
   (teal       '("#2F8F8B" "brightgreen" "brightgreen"))
   (yellow     '("#B58900" "yellow" "yellow"))
   (blue       '("#3A7BD5" "brightblue" "brightblue"))
   (pink       '("#C05A8C" "magenta" "magenta"))
   (purple     '("#7C6EE6" "brightmagenta" "brightmagenta"))
   (magenta    pink)
   (violet     purple)
   (cyan       '("#2F8F8B" "brightcyan" "brightcyan"))
   (dark-cyan  '("#2F8F8B" "cyan" "cyan"))

   (highlight  blue)
   (vertical-bar border)
   (selection  '("#E6DCC8" "brightblack" "brightblack"))
   (dark-blue  selection)
   (builtin    pink)
   (comments   muted)
   (doc-comments subtle)
   (constants  pink)
   (functions  blue)
   (keywords   purple)
   (methods    blue)
   (operators  purple)
   (type       cyan)
   (strings    green)
   (variables  fg)
   (numbers    orange)
   (region     selection)
   (error      red)
   (warning    yellow)
   (success    green)
   (vc-modified orange)
   (vc-added   green)
   (vc-deleted red)

   (modeline-fg              fg)
   (modeline-fg-alt          muted)
   (modeline-bg              "#EAE5DC")
   (modeline-bg-inactive     "#D6D0C4")
   (popup-bg                 "#EAE5DC")
   (popup-selection          "#E6DCC8")
   (diff-add-bg              "#DCEEDB")
   (diff-change-bg           "#E8E1F3")
   (diff-delete-bg           "#F3D9D9")
   )

  (((line-number &override)
    :foreground subtle)
   ((line-number-current-line &override)
    :foreground fg)

   ;;;; Syntax
   ((font-lock-builtin-face &override)
    :foreground blue :slant 'italic :weight 'normal)
   ((font-lock-comment-face &override)
    :foreground comments :slant 'italic :weight 'normal)
   ((font-lock-constant-face &override)
    :foreground constants :slant 'normal :weight 'normal)
   ((font-lock-doc-face &override)
    :foreground doc-comments :slant 'italic :weight 'normal)
   ((font-lock-function-name-face &override)
    :foreground functions :slant 'normal :weight 'normal)
   ((font-lock-function-call-face &override)
    :foreground functions :slant 'normal :weight 'normal)
   ((font-lock-keyword-face &override)
    :foreground keywords :slant 'normal :weight 'normal)
   ((font-lock-number-face &override)
    :foreground numbers :slant 'normal :weight 'normal)
   ((font-lock-operator-face &override)
    :foreground operators :slant 'normal :weight 'normal)
   ((font-lock-preprocessor-face &override)
    :foreground constants :slant 'normal :weight 'normal)
   ((font-lock-property-name-face &override)
    :foreground variables :slant 'normal :weight 'normal)
   ((font-lock-property-use-face &override)
    :foreground variables :slant 'normal :weight 'normal)
   ((font-lock-punctuation-face &override)
    :foreground subtle :slant 'normal :weight 'normal)
   ((font-lock-string-face &override)
    :foreground strings :slant 'normal :weight 'normal)
   ((font-lock-type-face &override)
    :foreground type :slant 'normal :weight 'normal)
   ((font-lock-variable-name-face &override)
    :foreground variables :slant 'normal :weight 'normal)
   ((font-lock-variable-use-face &override)
    :foreground variables :slant 'normal :weight 'normal)

   ;;;; Eglot semantic tokens
   (eglot-semantic-namespace :foreground cyan)
   (eglot-semantic-type :foreground cyan)
   (eglot-semantic-class :foreground cyan)
   (eglot-semantic-enum :foreground cyan)
   (eglot-semantic-interface :foreground cyan)
   (eglot-semantic-struct :foreground cyan)
   (eglot-semantic-typeParameter :foreground cyan)
   (eglot-semantic-parameter :foreground fg)
   (eglot-semantic-variable :foreground fg)
   (eglot-semantic-property :foreground fg)
   (eglot-semantic-enumMember :foreground pink)
   (eglot-semantic-event :foreground cyan)
   (eglot-semantic-function :foreground blue)
   (eglot-semantic-method :foreground blue)
   (eglot-semantic-macro :foreground pink :slant 'italic)
   (eglot-semantic-keyword :foreground purple)
   (eglot-semantic-modifier :foreground purple)
   (eglot-semantic-comment :foreground muted :slant 'italic)
   (eglot-semantic-string :foreground green)
   (eglot-semantic-number :foreground orange)
   (eglot-semantic-regexp :foreground pink)
   (eglot-semantic-operator :foreground purple)
   (eglot-semantic-decorator :foreground pink)
   (eglot-semantic-declaration :inherit nil :weight 'bold)
   (eglot-semantic-definition :inherit nil :weight 'bold)
   (eglot-semantic-readonly :inherit nil :foreground pink)
   (eglot-semantic-static :inherit nil :foreground pink :slant 'italic)
   (eglot-semantic-abstract :inherit nil :slant 'italic)
   (eglot-semantic-async :inherit nil :slant 'italic)
   (eglot-semantic-modification :inherit nil :underline t)
   (eglot-semantic-documentation :inherit nil :slant 'italic)
   (eglot-semantic-defaultLibrary
    :inherit nil :foreground blue :slant 'italic)

   ;;;; Editor chrome
   (cursor
    :background fg)
   (mode-line
    :background modeline-bg
    :foreground modeline-fg)
   (mode-line-inactive
    :background modeline-bg-inactive
    :foreground modeline-fg-alt)
   (mode-line-emphasis
    :foreground blue)
   (doom-modeline-bar
    :background blue)
   (doom-modeline-bar-inactive
    :background border)

   ;;;; Corfu
   (corfu-default
    :background popup-bg
    :foreground fg)
   (corfu-current
    :background popup-selection
    :foreground fg
    :weight 'bold)
   (corfu-border
    :background border)
   (corfu-annotations
    :foreground muted)
   (corfu-deprecated
    :foreground red
    :strike-through t)
   (corfu-bar
    :background blue)

   ;;;; Vertico and completion
   (vertico-current
    :background popup-selection
    :foreground fg
    :extend t)
   (orderless-match-face-0 :foreground blue :weight 'bold)
   (orderless-match-face-1 :foreground purple :weight 'bold)
   (orderless-match-face-2 :foreground green :weight 'bold)
   (orderless-match-face-3 :foreground yellow :weight 'bold)
   (marginalia-documentation :foreground muted)
   (marginalia-file-name :foreground fg)
   (marginalia-size :foreground subtle)
   (marginalia-modified :foreground orange)

   ;;;; Dashboard
   (dashboard-heading :foreground purple :weight 'bold)
   (dashboard-items-face :foreground fg)
   (dashboard-no-items-message :foreground muted)
   (dashboard-banner-logo-title :foreground blue :weight 'bold)
   (dashboard-footer :foreground subtle)

   ;;;; Magit and Transient
   (magit-section-heading :foreground blue :weight 'bold :extend t)
   (magit-section-heading-selection :foreground orange :weight 'bold :extend t)
   (magit-section-highlight :inherit 'hl-line)
   (magit-diff-added :foreground green :background diff-add-bg :extend t)
   (magit-diff-added-highlight :foreground green :background diff-add-bg :weight 'bold :extend t)
   (magit-diff-removed :foreground red :background diff-delete-bg :extend t)
   (magit-diff-removed-highlight :foreground red :background diff-delete-bg :weight 'bold :extend t)
   (magit-diff-context-highlight :background bg-alt :foreground fg :extend t)
   (magit-diff-hunk-heading :background diff-change-bg :foreground purple :extend t)
   (magit-diff-hunk-heading-highlight :background purple :foreground bg :weight 'bold :extend t)
   (magit-header-line :background selection :foreground fg :weight 'bold)
   (magit-dimmed :foreground muted)
   (transient-heading :foreground purple :weight 'bold)
   (transient-key :foreground blue :weight 'bold)
   (transient-value :foreground green :weight 'bold)
   (transient-inactive-argument :foreground muted)
   (transient-inactive-value :foreground muted)

   ;;;; Diagnostics and editor states
   (flymake-error :underline `(:style wave :color ,red))
   (flymake-warning :underline `(:style wave :color ,yellow))
   (flymake-note :underline `(:style wave :color ,info))
   (hl-line :background bg-alt :extend t)
   (hl-todo :foreground red :weight 'bold)
   (whitespace-trailing :background diff-delete-bg)
   (whitespace-tab :background base0)
   (whitespace-indentation :background base0)

   ;;;; Org and Markdown
   ((org-block &override) :background base2 :extend t)
   ((org-block-begin-line &override) :background base2 :foreground muted :extend t)
   ((org-block-end-line &override) :background base2 :foreground muted :extend t)
   (org-code :foreground orange)
   (org-link :foreground blue :underline t)
   (org-todo :foreground green :weight 'bold)
   (org-done :foreground muted :strike-through nil)
   (markdown-header-face :foreground purple :weight 'bold)
   (markdown-markup-face :foreground subtle)
   ((markdown-code-face &override) :background base2)

   ;;;; Dired, Evil and version control
   (dired-directory :foreground blue :weight 'bold)
   (dired-symlink :foreground cyan)
   (evil-ex-lazy-highlight :inherit 'lazy-highlight)
   (diff-added :foreground green :background diff-add-bg)
   (diff-removed :foreground red :background diff-delete-bg)
   (diff-changed :foreground purple :background diff-change-bg))

  ())

;;; helsing-theme.el ends here
