-- helsing.lua
-- Generated from docs/helsing-palette.yml via generator/generate.py.
-- Do not edit this file by hand unless you are intentionally diverging from the generator.

if vim.g.colors_name then
  vim.cmd("highlight clear")
end

if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end

vim.o.background = "light"
vim.g.colors_name = "helsing"

local c = {
  -- Base
  bg        = "#F4F1EA",
  bg_alt    = "#EAE5DC",
  fg        = "#2A2A2A",
  muted     = "#6B6B6B",
  subtle    = "#A8A29E",
  border    = "#D6D0C4",
  selection = "#E6DCC8",

  -- Accents
  purple    = "#7C6EE6",
  blue      = "#3A7BD5",
  green     = "#4C9A5F",
  orange    = "#C47A2C",
  cyan      = "#2F8F8B",
  pink      = "#C05A8C",
  red       = "#C23B3B",
  yellow    = "#B58900",
  info      = "#4A90E2",

  -- Extra UI tones
  diff_add    = "#DCEEDB",
  diff_change = "#E8E1F3",
  diff_delete = "#F3D9D9",
  search      = "#F1E7B8",
  incsearch   = "#E8D58B",
  cursorline  = "#EFE9DF",
  linenr      = "#B3ADA4",
  visual      = "#E6DCC8",
  pmenu       = "#ECE7DE",
  pmenu_sel   = "#DDD4C5",
}

local function hl(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

local function link(group, target)
  hl(group, { link = target })
end

-- Editor UI
hl("Normal",       { fg = c.fg, bg = c.bg })
hl("NormalNC",     { fg = c.fg, bg = c.bg })
hl("NormalFloat",  { fg = c.fg, bg = c.bg_alt })
hl("FloatBorder",  { fg = c.border, bg = c.bg_alt })
hl("FloatTitle",   { fg = c.blue, bg = c.bg_alt, bold = true })
hl("FloatFooter",  { fg = c.muted, bg = c.bg_alt })
hl("ColorColumn",  { bg = c.bg_alt })
hl("Cursor",       { fg = c.bg, bg = c.fg })
hl("CursorIM",     { fg = c.bg, bg = c.fg })
hl("lCursor",      { fg = c.bg, bg = c.fg })
hl("TermCursor",   { fg = c.bg, bg = c.fg })
hl("TermCursorNC", { fg = c.bg, bg = c.subtle })
hl("CursorLine",   { bg = c.cursorline })
hl("CursorColumn", { bg = c.cursorline })
hl("CursorLineNr", { fg = c.orange, bg = c.cursorline, bold = true })
hl("CursorLineFold", { fg = c.subtle, bg = c.cursorline })
hl("CursorLineSign", { fg = c.subtle, bg = c.cursorline })
hl("LineNr",       { fg = c.linenr, bg = c.bg })
hl("LineNrAbove",  { fg = c.linenr, bg = c.bg })
hl("LineNrBelow",  { fg = c.linenr, bg = c.bg })
hl("SignColumn",   { fg = c.subtle, bg = c.bg })
hl("EndOfBuffer",  { fg = c.border, bg = c.bg })
hl("VertSplit",    { fg = c.border, bg = c.bg })
hl("WinSeparator", { fg = c.border, bg = c.bg })
hl("WinBar",       { fg = c.muted, bg = c.bg })
hl("WinBarNC",     { fg = c.subtle, bg = c.bg })
hl("Folded",       { fg = c.muted, bg = c.bg_alt })
hl("FoldColumn",   { fg = c.subtle, bg = c.bg })
hl("MatchParen",   { fg = c.red, bg = c.selection, bold = true })
hl("Visual",       { bg = c.visual })
hl("VisualNOS",    { bg = c.visual })
hl("Search",       { fg = c.fg, bg = c.search })
hl("IncSearch",    { fg = c.fg, bg = c.incsearch, bold = true })
hl("CurSearch",    { fg = c.fg, bg = c.incsearch, bold = true })
hl("Substitute",   { fg = c.bg, bg = c.orange, bold = true })
hl("Pmenu",        { fg = c.fg, bg = c.pmenu })
hl("PmenuSel",     { fg = c.fg, bg = c.pmenu_sel, bold = true })
hl("PmenuKind",    { fg = c.cyan, bg = c.pmenu })
hl("PmenuKindSel", { fg = c.cyan, bg = c.pmenu_sel, bold = true })
hl("PmenuExtra",   { fg = c.muted, bg = c.pmenu })
hl("PmenuExtraSel",{ fg = c.muted, bg = c.pmenu_sel })
hl("PmenuMatch",   { fg = c.blue, bg = c.pmenu, bold = true })
hl("PmenuMatchSel",{ fg = c.blue, bg = c.pmenu_sel, bold = true })
hl("PmenuSbar",    { bg = c.bg_alt })
hl("PmenuThumb",   { bg = c.subtle })
hl("ComplMatchIns",{ fg = c.blue, bold = true, underline = true })
hl("StatusLine",   { fg = c.fg, bg = c.bg_alt })
hl("StatusLineNC", { fg = c.muted, bg = c.bg_alt })
hl("StatusLineTerm",   { fg = c.fg, bg = c.bg_alt })
hl("StatusLineTermNC", { fg = c.muted, bg = c.bg_alt })
hl("TabLine",      { fg = c.muted, bg = c.bg_alt })
hl("TabLineFill",  { bg = c.bg_alt })
hl("TabLineSel",   { fg = c.fg, bg = c.bg, bold = true })
hl("Title",        { fg = c.blue, bold = true })
hl("Directory",    { fg = c.blue, bold = true })
hl("QuickFixLine", { bg = c.selection, bold = true })
hl("Conceal",      { fg = c.subtle })
hl("WildMenu",     { fg = c.fg, bg = c.selection, bold = true })
hl("MsgArea",      { fg = c.fg, bg = c.bg })
hl("MsgSeparator", { fg = c.border, bg = c.bg })
hl("NonText",      { fg = c.border })
hl("Whitespace",   { fg = c.border })
hl("SpecialKey",   { fg = c.subtle })
hl("ErrorMsg",     { fg = c.red, bold = true })
hl("WarningMsg",   { fg = c.yellow, bold = true })
hl("ModeMsg",      { fg = c.blue, bold = true })
hl("MoreMsg",      { fg = c.blue })
hl("Question",     { fg = c.cyan, bold = true })
hl("SnippetTabstop", { bg = c.selection })
hl("Terminal",     { fg = c.fg, bg = c.bg })
hl("Menu",         { fg = c.fg, bg = c.bg_alt })
hl("Scrollbar",    { fg = c.subtle, bg = c.bg_alt })
hl("Tooltip",      { fg = c.fg, bg = c.bg_alt })
hl("User1",        { fg = c.blue, bg = c.bg_alt, bold = true })
hl("User2",        { fg = c.purple, bg = c.bg_alt, bold = true })
hl("User3",        { fg = c.cyan, bg = c.bg_alt, bold = true })
hl("User4",        { fg = c.green, bg = c.bg_alt, bold = true })
hl("User5",        { fg = c.orange, bg = c.bg_alt, bold = true })
hl("User6",        { fg = c.pink, bg = c.bg_alt, bold = true })
hl("User7",        { fg = c.yellow, bg = c.bg_alt, bold = true })
hl("User8",        { fg = c.red, bg = c.bg_alt, bold = true })
hl("User9",        { fg = c.fg, bg = c.bg_alt, bold = true })

-- Syntax
hl("Comment",      { fg = c.muted, italic = true })
hl("Constant",     { fg = c.pink })
hl("String",       { fg = c.green })
hl("Character",    { fg = c.green })
hl("Number",       { fg = c.orange })
hl("Boolean",      { fg = c.orange, bold = true })
hl("Float",        { fg = c.orange })
hl("Identifier",   { fg = c.fg })
hl("Function",     { fg = c.blue })
hl("Statement",    { fg = c.purple })
hl("Conditional",  { fg = c.purple })
hl("Repeat",       { fg = c.purple })
hl("Label",        { fg = c.purple })
hl("Operator",     { fg = c.red })
hl("Keyword",      { fg = c.purple })
hl("Exception",    { fg = c.purple })
hl("PreProc",      { fg = c.pink })
hl("Include",      { fg = c.purple })
hl("Define",       { fg = c.pink })
hl("Macro",        { fg = c.pink })
hl("PreCondit",    { fg = c.pink })
hl("Type",         { fg = c.cyan })
hl("StorageClass", { fg = c.cyan })
hl("Structure",    { fg = c.cyan })
hl("Typedef",      { fg = c.cyan })
hl("Special",      { fg = c.red })
hl("SpecialChar",  { fg = c.red })
hl("Tag",          { fg = c.blue })
hl("Delimiter",    { fg = c.subtle })
hl("SpecialComment", { fg = c.muted, italic = true })
hl("Debug",        { fg = c.red })
hl("Underlined",   { underline = true })
hl("Bold",         { bold = true })
hl("Italic",       { italic = true })
hl("Error",        { fg = c.red, bold = true })
hl("Todo",         { fg = c.yellow, bg = c.bg_alt, bold = true })

-- Diagnostics
hl("DiagnosticError",            { fg = c.red })
hl("DiagnosticWarn",             { fg = c.yellow })
hl("DiagnosticInfo",             { fg = c.info })
hl("DiagnosticHint",             { fg = c.cyan })
hl("DiagnosticOk",               { fg = c.green })

hl("DiagnosticUnderlineError",   { undercurl = true, sp = c.red })
hl("DiagnosticUnderlineWarn",    { undercurl = true, sp = c.yellow })
hl("DiagnosticUnderlineInfo",    { undercurl = true, sp = c.info })
hl("DiagnosticUnderlineHint",    { undercurl = true, sp = c.cyan })

hl("DiagnosticVirtualTextError", { fg = c.red, bg = c.bg_alt })
hl("DiagnosticVirtualTextWarn",  { fg = c.yellow, bg = c.bg_alt })
hl("DiagnosticVirtualTextInfo",  { fg = c.info, bg = c.bg_alt })
hl("DiagnosticVirtualTextHint",  { fg = c.cyan, bg = c.bg_alt })
hl("DiagnosticVirtualTextOk",    { fg = c.green, bg = c.bg_alt })

hl("DiagnosticVirtualLinesError",{ fg = c.red, bg = c.bg_alt })
hl("DiagnosticVirtualLinesWarn", { fg = c.yellow, bg = c.bg_alt })
hl("DiagnosticVirtualLinesInfo", { fg = c.info, bg = c.bg_alt })
hl("DiagnosticVirtualLinesHint", { fg = c.cyan, bg = c.bg_alt })
hl("DiagnosticVirtualLinesOk",   { fg = c.green, bg = c.bg_alt })

hl("DiagnosticFloatingError",    { fg = c.red, bg = c.bg_alt })
hl("DiagnosticFloatingWarn",     { fg = c.yellow, bg = c.bg_alt })
hl("DiagnosticFloatingInfo",     { fg = c.info, bg = c.bg_alt })
hl("DiagnosticFloatingHint",     { fg = c.cyan, bg = c.bg_alt })
hl("DiagnosticFloatingOk",       { fg = c.green, bg = c.bg_alt })

hl("DiagnosticSignError",        { fg = c.red, bg = c.bg })
hl("DiagnosticSignWarn",         { fg = c.yellow, bg = c.bg })
hl("DiagnosticSignInfo",         { fg = c.info, bg = c.bg })
hl("DiagnosticSignHint",         { fg = c.cyan, bg = c.bg })
hl("DiagnosticSignOk",           { fg = c.green, bg = c.bg })

hl("DiagnosticDeprecated",       { fg = c.muted, strikethrough = true })
hl("DiagnosticUnnecessary",      { fg = c.subtle, italic = true })
hl("DiagnosticUnderlineOk",      { undercurl = true, sp = c.green })
hl("LspReferenceText",           { bg = c.selection })
hl("LspReferenceRead",           { bg = c.selection })
hl("LspReferenceWrite",          { bg = c.selection, bold = true })
hl("LspReferenceTarget",         { bg = c.selection, underline = true })
hl("LspCodeLens",                { fg = c.subtle, italic = true })
hl("LspCodeLensSeparator",       { fg = c.border })
hl("LspInlayHint",               { fg = c.muted, bg = c.bg_alt, italic = true })
hl("LspSignatureActiveParameter",{ fg = c.orange, bold = true, underline = true })

-- Diff / Git
hl("DiffAdd",    { bg = c.diff_add })
hl("DiffChange", { bg = c.diff_change })
hl("DiffDelete", { bg = c.diff_delete })
hl("DiffText",   { bg = c.selection, bold = true })

hl("Added",      { fg = c.green })
hl("Changed",    { fg = c.purple })
hl("Removed",    { fg = c.red })

-- Spelling
hl("SpellBad",   { undercurl = true, sp = c.red })
hl("SpellCap",   { undercurl = true, sp = c.blue })
hl("SpellRare",  { undercurl = true, sp = c.purple })
hl("SpellLocal", { undercurl = true, sp = c.cyan })

-- Treesitter fallbacks
link("@comment",             "Comment")
link("@comment.documentation","Comment")
link("@comment.error",       "DiagnosticError")
link("@comment.warning",     "DiagnosticWarn")
link("@comment.note",        "DiagnosticInfo")
link("@comment.todo",        "Todo")
link("@constant",            "Constant")
hl("@constant.builtin",    { fg = c.pink, italic = true })
hl("@constant.macro",      { fg = c.pink, italic = true })
hl("@string",              { link = "String" })
hl("@string.escape",       { fg = c.red })
hl("@string.regexp",       { fg = c.red })
hl("@string.special",      { fg = c.green, italic = true })
hl("@string.special.path", { fg = c.green, underline = true })
hl("@string.special.url",  { fg = c.blue, underline = true })
link("@character",           "Character")
hl("@character.special",   { fg = c.red })
link("@number",              "Number")
link("@boolean",             "Boolean")
link("@function",            "Function")
link("@function.call",       "Function")
hl("@function.builtin",    { fg = c.blue, italic = true })
hl("@function.macro",      { fg = c.pink, italic = true })
hl("@method",              { fg = c.blue })
hl("@method.call",         { fg = c.blue })
hl("@constructor",         { fg = c.cyan })
hl("@module",              { fg = c.cyan })
hl("@namespace",           { fg = c.cyan })
hl("@parameter",           { fg = c.fg })
hl("@variable.parameter",  { fg = c.fg })
hl("@variable.member",     { fg = c.fg })
link("@keyword",             "Keyword")
hl("@keyword.function",    { fg = c.purple })
hl("@keyword.operator",    { fg = c.purple })
hl("@keyword.import",      { fg = c.purple })
hl("@keyword.exception",   { fg = c.purple })
hl("@keyword.directive",   { fg = c.pink })
hl("@keyword.return",      { fg = c.purple, italic = true })
link("@conditional",         "Conditional")
link("@repeat",              "Repeat")
link("@operator",            "Operator")
link("@type",                "Type")
hl("@type.builtin",        { fg = c.cyan, italic = true })
hl("@type.definition",     { fg = c.cyan })
hl("@type.qualifier",      { fg = c.purple })
hl("@attribute",           { fg = c.orange })
hl("@property",            { fg = c.fg })
hl("@field",               { fg = c.fg })
hl("@variable",            { fg = c.fg })
hl("@variable.builtin",    { fg = c.red, italic = true })
hl("@punctuation.delimiter", { fg = c.subtle })
hl("@punctuation.bracket", { fg = c.subtle })
hl("@punctuation.special", { fg = c.subtle })
link("@tag",                 "Tag")
hl("@tag.attribute",       { fg = c.orange })
hl("@tag.delimiter",       { fg = c.subtle })
hl("@markup.strong",       { bold = true })
hl("@markup.italic",       { italic = true })
hl("@markup.strikethrough",{ strikethrough = true })
hl("@markup.heading",      { fg = c.blue, bold = true })
hl("@markup.heading.1",    { fg = c.blue, bold = true })
hl("@markup.heading.2",    { fg = c.purple, bold = true })
hl("@markup.heading.3",    { fg = c.cyan, bold = true })
hl("@markup.heading.4",    { fg = c.green, bold = true })
hl("@markup.heading.5",    { fg = c.orange, bold = true })
hl("@markup.heading.6",    { fg = c.pink, bold = true })
hl("@markup.link",         { fg = c.blue, underline = true })
hl("@markup.link.url",     { fg = c.blue, underline = true })
hl("@markup.raw",          { fg = c.green })
hl("@markup.raw.block",    { fg = c.green })
hl("@markup.list",         { fg = c.red })
hl("@markup.quote",        { fg = c.muted, italic = true })
hl("@diff.plus",           { fg = c.green })
hl("@diff.minus",          { fg = c.red })
hl("@diff.delta",          { fg = c.purple })

-- LSP semantic tokens
link("@lsp.type.class",          "@type")
link("@lsp.type.comment",        "@comment")
link("@lsp.type.decorator",      "@attribute")
link("@lsp.type.enum",           "@type")
link("@lsp.type.enumMember",     "@constant")
link("@lsp.type.event",          "@type")
link("@lsp.type.function",       "@function")
link("@lsp.type.interface",      "@type")
link("@lsp.type.keyword",        "@keyword")
link("@lsp.type.macro",          "@function.macro")
link("@lsp.type.method",         "@method")
link("@lsp.type.modifier",       "@keyword")
link("@lsp.type.namespace",      "@namespace")
link("@lsp.type.number",         "@number")
link("@lsp.type.operator",       "@operator")
link("@lsp.type.parameter",      "@parameter")
link("@lsp.type.property",       "@property")
link("@lsp.type.regexp",         "@string.regexp")
link("@lsp.type.string",         "@string")
link("@lsp.type.struct",         "@type")
link("@lsp.type.type",           "@type")
link("@lsp.type.typeParameter",  "@type")
link("@lsp.type.variable",       "@variable")
hl("@lsp.mod.abstract",          { italic = true })
hl("@lsp.mod.async",             { fg = c.blue, italic = true })
hl("@lsp.mod.declaration",       { bold = true })
hl("@lsp.mod.defaultLibrary",    { fg = c.blue, italic = true })
hl("@lsp.mod.definition",        { bold = true })
link("@lsp.mod.deprecated",      "DiagnosticDeprecated")
hl("@lsp.mod.documentation",     { fg = c.muted, italic = true })
hl("@lsp.mod.modification",      { underline = true })
hl("@lsp.mod.readonly",          { fg = c.pink })
hl("@lsp.mod.static",            { fg = c.pink, italic = true })

-- Common plugin groups
hl("GitSignsAdd",          { fg = c.green, bg = c.bg })
hl("GitSignsChange",       { fg = c.purple, bg = c.bg })
hl("GitSignsDelete",       { fg = c.red, bg = c.bg })

hl("TelescopeNormal",      { fg = c.fg, bg = c.bg_alt })
hl("TelescopeBorder",      { fg = c.border, bg = c.bg_alt })
hl("TelescopePromptNormal",{ fg = c.fg, bg = c.bg_alt })
hl("TelescopePromptBorder",{ fg = c.border, bg = c.bg_alt })
hl("TelescopeSelection",   { bg = c.selection, bold = true })
hl("TelescopeMatching",    { fg = c.blue, bold = true })

hl("NvimTreeNormal",       { fg = c.fg, bg = c.bg_alt })
hl("NvimTreeWinSeparator", { fg = c.border, bg = c.bg_alt })
hl("NvimTreeRootFolder",   { fg = c.blue, bold = true })
hl("NvimTreeFolderName",   { fg = c.blue })
hl("NvimTreeOpenedFolderName", { fg = c.blue, bold = true })
hl("NvimTreeEmptyFolderName",  { fg = c.muted })
hl("NvimTreeIndentMarker", { fg = c.border })

hl("WhichKey",             { fg = c.purple })
hl("WhichKeyGroup",        { fg = c.blue })
hl("WhichKeyDesc",         { fg = c.fg })
hl("WhichKeySeparator",    { fg = c.subtle })
hl("WhichKeyFloat",        { bg = c.bg_alt })

-- Markdown
hl("markdownH1",           { fg = c.blue, bold = true })
hl("markdownH2",           { fg = c.purple, bold = true })
hl("markdownH3",           { fg = c.cyan, bold = true })
hl("markdownCode",         { fg = c.green })
hl("markdownCodeBlock",    { fg = c.green })
hl("markdownItalic",       { italic = true })
hl("markdownBold",         { bold = true })
hl("markdownUrl",          { fg = c.blue, underline = true })
