-- Helsing integration for bufferline.nvim.
-- Generated from the Helsing Neovim target; do not edit this file directly.

local M = {}

local function highlight_colors(name)
  local source = vim.api.nvim_get_hl(0, { name = name, link = false })
  local result = {}

  for _, attribute in ipairs({ "fg", "bg", "sp" }) do
    if source[attribute] then
      result[attribute] = string.format("#%06x", source[attribute])
    end
  end

  return result
end

function M.apply(opts)
  if vim.g.colors_name ~= "helsing" then
    return opts
  end

  opts = opts or {}
  local inherited = opts.highlights

  opts.highlights = function(defaults)
    local default_highlights = defaults.highlights or defaults
    local base = default_highlights

    if type(inherited) == "function" then
      base = inherited(defaults) or default_highlights
    elseif type(inherited) == "table" then
      base = vim.tbl_deep_extend("force", {}, default_highlights, inherited)
    end

    return vim.tbl_deep_extend("force", {}, base, {
      background = highlight_colors("BufferLineBackground"),
      buffer = highlight_colors("BufferLineBuffer"),
      buffer_visible = highlight_colors("BufferLineBufferVisible"),
      buffer_selected = highlight_colors("BufferLineBufferSelected"),
    })
  end

  return opts
end

return M
